
on:
  push:
    branches:
      - master




jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: "docker login"
        run: docker login --username ${{secrets.USERNAME_DOCKER}} --password ${{secrets.DOCKER_TOKEN}}
      - name: "building image"
        run: docker build -t ${{secrets.USERNAME_DOCKER}}/myimagesection3 .
      - name: "pushing image"
        run: docker push ${{secrets.USERNAME_DOCKER}}/myimagesection3
     